# Generated by Django 3.2.8 on 2022-04-22 16:33

from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('theme', models.CharField(max_length=255, verbose_name='Theme')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pin')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Course name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('about', models.TextField(verbose_name='About')),
                ('contact', models.CharField(max_length=255, verbose_name='Contact')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, size=[400, 350], upload_to='', verbose_name='Choose image main (format: jpg, jpeg, png)')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.CharField(max_length=655, verbose_name='Answer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors', models.IntegerField(default=0, verbose_name='Visitors')),
                ('visits', models.IntegerField(default=0, verbose_name='Visits')),
                ('registerated', models.IntegerField(default=0, verbose_name='Registerated')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, size=[800, 600], upload_to='', verbose_name='Choose image main (format: jpg, jpeg, png)')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=255)),
                ('phone2', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255, verbose_name='@Facebook')),
                ('youtube', models.CharField(max_length=255, verbose_name='@Youtube')),
                ('instagram', models.CharField(max_length=255, verbose_name='@Instagram')),
                ('telegram', models.CharField(max_length=255, verbose_name='@Telegram')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255, verbose_name='Teacher name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('about', models.TextField(verbose_name='About')),
                ('contact', models.CharField(max_length=255, verbose_name='@Contact')),
                ('facebook', models.CharField(max_length=255, verbose_name='@Facebook')),
                ('instagram', models.CharField(max_length=255, verbose_name='@Instagram')),
                ('twitter', models.CharField(max_length=255, verbose_name='@Twitter')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, size=[400, 350], upload_to='', verbose_name='Choose image main (format: jpg, jpeg, png)')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
