# Generated by Django 3.2.8 on 2022-04-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.CharField(default='%d.%m.%y', max_length=255, verbose_name='Timestamp'),
        ),
    ]
