# Generated by Django 3.2.8 on 2022-04-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220422_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is New'),
        ),
    ]
